### ISSUE TITLE
hello , no issue , just a sugestion to check if it's possible

### ISSUE THREAD

**Issue by Maureks** [MaDHouSe79/qb-aimedic#2]
Hey , is it possible , to add an option for the medic bot , to check the status of the player first, and if the player had died of bullet wounds ,  then not revive him ?

Thanks for the attention !

**Comment by MaDHouSe79** [comment]
i'm on that, but i have some delay now but it is coming soon ;)

**Comment by RenggoStarz** [comment]
![image](https://user-images.githubusercontent.com/103148666/162617507-de0f80a4-b984-4d5c-9729-714cfa682267.png)
i have this error

**Comment by MaDHouSe79** [comment]
did you just spawn in witout a saved character?cause it checks if you have money, and if yopur character is not saved of dont have money table or have no tables at all, it wil not work.

**Comment by RenggoStarz** [comment]
it work .. this script can do auto revive.. when player dead auto revive. i mean no medic in game auto revive player dead
