### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by MadManDanCat** [MaDHouSe79/qb-aimedic#4]
all that stuff in config but doesnt work ... this is basically just a /revive for normal people there is no medic no ambulance really bad script

**Comment by MadManDanCat** [comment]
sense* not sence my server is not poorly installed every other script i have works i was just mentioning you have in the config about spawn distance etc but you dont even have the car spawning code implemented it just revives you on the spot learn 2 code

**Comment by MaDHouSe79** [comment]
learn to code? says the person who downloads and uses my script, if you can do it yourself why do you download it? 
bit vague behavior... lol

**Comment by MadManDanCat** [comment]
Why write it if someone has already written it .... yet you haven't ive seen this code before you copy pasted most of it and not very well.
